--- 
addons: ~
apt: ~
before_install: 
  - "chmod +x configure"
  - "chmod +x cleanup"
brew_packages: 
  - udunits
dist: trusty
exclude: 
  - 
    os: osx
jobs: ~
language: ry
os: 
  - linux
  - osx
osx_image: xcode9.4
packages: 
  - libudunits2-dev
  - gdal-bin
  - libgdal1-dev
  - libproj-dev
r: devel
r_build_args: "--no-build-vignettes"
r_packages: 
  - knitr
  - rmarkdown
  - ggplot2
  - ggvoronoi
  - sampling
  - BalancedSampling
  - sp
  - sf
warnings_are_errors: false