# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @encoding UTF-8
#' @title systematic desgin
#'
#' @description
#'
#' Find all possible systematic sample from a vector of inclusion probabilities \code{pik}.
#'
#' @param pik vector of inclusion probabilities..
#'
#' @return A matrix of size at most N x N with elements equal to 0 or 1. The value 1 indicates that the uni is selected while the value 0 is for non-chosen unit.
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @export
systematicDesign <- function(pik) {
    .Call(`_Sampling_systematicDesign`, pik)
}

