# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

all0 <- function(x) {
    .Call(`_Sampling_all0`, x)
}

#' @title title
#'
#' @description
#' description
#'
#'
#' @param x x
#'
#' @details
#'
#' details
#'
#' @return a vector
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @seealso
#' func
#'
#' @examples
#'
#' @export
rrefBal <- function(M) {
    invisible(.Call(`_Sampling_rrefBal`, M))
}

#' @title title
#'
#' @description
#' description
#'
#'
#' @param x x
#'
#' @details
#'
#' details
#'
#' @return a vector
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @seealso
#' func
#'
#' @examples
#'
#' @export
ukern <- function(Bm) {
    .Call(`_Sampling_ukern`, Bm)
}

#' @title title
#'
#' @description
#' description
#'
#'
#' @param x x
#'
#' @details
#'
#' details
#'
#' @return a vector
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @seealso
#' func
#'
#' @examples
#'
#' @export
onestepfastflightcube <- function(prob, Bm) {
    .Call(`_Sampling_onestepfastflightcube`, prob, Bm)
}

#' @title title
#'
#' @description
#' description
#'
#'
#' @param x x
#'
#' @details
#'
#' details
#'
#' @return a vector
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @seealso
#' func
#'
#' @examples
#'
#' @export
flightphase <- function(prob, Xbal) {
    .Call(`_Sampling_flightphase`, prob, Xbal)
}

#' @title Arma matrix to NumericMatrix
#'
#' @param x Matrix X
#'
#' @return same matrix
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
NULL

#' @title NumericMatrix matrix to Arma
#'
#' @param x Matrix X
#'
#' @return same matrix
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
NULL

#' @title NumericMatrix matrix to Arma
#'
#' @param x Matrix X
#'
#' @return same matrix
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
NULL

#'
#' @export
mat_as_Numeric <- function(x) {
    .Call(`_Sampling_mat_as_Numeric`, x)
}

#'
#' @export
mat_as_arma <- function(x) {
    .Call(`_Sampling_mat_as_arma`, x)
}

#'
#' @export
svdArma <- function(x) {
    .Call(`_Sampling_svdArma`, x)
}

#' @title Binomial coefficient
#'
#' @param n integer.
#' @param k integer.
#'
#'
#' @return binomial coefficient
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#'
#' @export
choose <- function(n, k) {
    .Call(`_Sampling_choose`, n, k)
}

#' @title Arma matrix to NumericMatrix
#'
#' @param x Matrix X
#'
#' @return same matrix
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
NULL

#' @title Arma matrix to NumericMatrix
#'
#' @param x Matrix X
#'
#' @return same matrix
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
NULL

#' @title Arma matrix to NumericMatrix
#'
#' @param x Matrix X
#'
#' @return same matrix
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
NULL

#' @title Arma matrix to NumericMatrix
#'
#' @param x Matrix X
#'
#' @return same matrix
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
NULL

#' @title Arma matrix to NumericMatrix
#'
#' @param x Matrix X
#'
#' @return same matrix
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
NULL

#' @title Arma matrix to NumericMatrix
#'
#' @param x Matrix X
#'
#' @return same matrix
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
NULL

#' @title Arma matrix to NumericMatrix
#'
#' @param x Matrix X
#'
#' @return same matrix
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
NULL

#' @title Arma matrix to NumericMatrix
#'
#' @param x Matrix X
#'
#' @return same matrix
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
NULL

#' @title Column sums for sparseMatrix
#'
#' @description
#' Form column sums for sparseMatrix.
#'
#' @param x A sparse matrix, i.e., inheriting from \code{\link[Matrix]{sparseMatrix}}.
#'
#' @details
#' This function is designed to be used for internal \code{RcppArmadillo} functions. Nevertheless it could be applied in R.
#' It loops on the non-zero entries of the \code{\link[Matrix]{sparseMatrix}}. For general uses, the function
#' \code{\link[Matrix]{colSums}} should be prefered.
#'
#' @return column sums of x.
#' 
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#' 
#' @seealso
#' \code{\link[Matrix]{colSums}}, \code{\link[Matrix]{rowSums}}.
#'
#' @export
reduxArma <- function(B) {
    .Call(`_Sampling_reduxArma`, B)
}

#'
#' @export
all_sug <- function(x) {
    .Call(`_Sampling_all_sug`, x)
}

#'
#' @export
colSumsRcpp <- function(x) {
    .Call(`_Sampling_colSumsRcpp`, x)
}

#'
#' @export
rowSumsRcpp <- function(x) {
    .Call(`_Sampling_rowSumsRcpp`, x)
}

#'
#' @export
reduxRcpp <- function(B) {
    .Call(`_Sampling_reduxRcpp`, B)
}

#'
#' @export
duplicatedMatrixRcpp <- function(x) {
    .Call(`_Sampling_duplicatedMatrixRcpp`, x)
}

#'
#' @export
check_equal <- function(x, y) {
    .Call(`_Sampling_check_equal`, x, y)
}

#'
#' @export
duplicatedCols <- function(B) {
    .Call(`_Sampling_duplicatedCols`, B)
}

#'
#' @export
duplicatedRows <- function(B) {
    .Call(`_Sampling_duplicatedRows`, B)
}

is_duplicate_row <- function(r, x) {
    .Call(`_Sampling_is_duplicate_row`, r, x)
}

#' @title title
#'
#' @description
#' description
#'
#'
#' @param x x
#'
#' @details
#'
#' details
#'
#' @return a vector
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @seealso
#' func
#'
#' @examples
#'
#' @export
flightphase_arma2 <- function(X, pik, EPS = 0.0000001) {
    .Call(`_Sampling_flightphase_arma2`, X, pik, EPS)
}

#' @title title
#'
#' @description
#' description
#'
#'
#' @param x x
#'
#' @details
#'
#' details
#'
#' @return a vector
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @seealso
#' func
#'
#' @examples
#'
#' @export
flightphase_arma <- function(X, pik, EPS = 0.0000001) {
    .Call(`_Sampling_flightphase_arma`, X, pik, EPS)
}

onestep <- function(B, pik, EPS = 0.0000001) {
    .Call(`_Sampling_onestep`, B, pik, EPS)
}

#' @title Column sums for sparseMatrix
#'
#' @description
#' Form column sums for sparseMatrix.
#'
#' @param x A sparse matrix, i.e., inheriting from \code{\link[Matrix]{sparseMatrix}}.
#'
#' @details
#' This function is designed to be used for internal \code{RcppArmadillo} functions. Nevertheless it could be applied in R.
#' It loops on the non-zero entries of the \code{\link[Matrix]{sparseMatrix}}. For general uses, the function
#' \code{\link[Matrix]{colSums}} should be prefered.
#'
#' @return column sums of x.
#' 
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#' 
#' @seealso
#' \code{\link[Matrix]{colSums}}, \code{\link[Matrix]{rowSums}}.
#'
#' @export
colSumsiter <- function(x) {
    .Call(`_Sampling_colSumsiter`, x)
}

#' @title Row sums on sparse matrix.
#'
#' @description
#' Form row sums for sparseMatrix.
#'
#' @param x A sparse matrix, i.e., inheriting from \code{\link[Matrix]{sparseMatrix}}.
#'
#' @details
#' This function is designed to be used for internal \code{RcppArmadillo} functions. Nevertheless it could be applied in R.
#' It loops on the non-zero entries of the \code{\link[Matrix]{sparseMatrix}}. For general uses, the function \code{\link[Matrix]{rowSums}} should
#' be prefered.
#'
#' @return row sums of x. 
#' 
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#' 
#' @seealso
#' \code{\link[Matrix]{colSums}}, \code{\link[Matrix]{rowSums}}.
#' 
#' @export
rowSumsiter <- function(x) {
    .Call(`_Sampling_rowSumsiter`, x)
}

#' @title All samples of fixed size
#'
#' @description
#' description Rosetta code combn
#'
#'
#' @param N population size
#' @param n sample size
#'
#'
#' @return a matrix of all samples of fixed size.
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#' 
#' @export
samplen <- function(N, n) {
    .Call(`_Sampling_samplen`, N, n)
}

#' @encoding UTF-8
#' @title systematic desgin
#'
#' @description
#'
#' Find all possible systematic sample from a vector of inclusion probabilities \code{pik}.
#'
#' @param pik vector of inclusion probabilities..
#'
#' @return A matrix of size at most N x N with elements equal to 0 or 1. The value 1 indicates that the uni is selected while the value 0 is for non-chosen unit.
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @export
systematicDesign <- function(pik) {
    .Call(`_Sampling_systematicDesign`, pik)
}

